### PR TITLE
Register path

### PR DESCRIPTION
**Pull request by jacobtipp**
I created a registerPath option in the config. I also added tests for GET/POST requests. If you'd like more/different tests let me know otherwise I was going to do the same thing for https://github.com/dwyl/hapi-login.

### CODE REVIEW

**Comment by nelsonic** [comment]
@traducer looks good. two things to add: 
1. A couple of lines in the readme informing people they can set the `registerPath` to what ever they need and
2. increase the package `version` in `package.json` to `1.1.0` so we can publish new version to NPM.

**Comment by jacobtipp** [comment]
Ok I updated the version to 1.1.0 and added some info in the README. I also made the same changes for Hapi-login. If there's anything else let me know!

**Comment by nelsonic** [comment]
Sweet! 🍭 
Thanks! 👍

**Comment by nelsonic** [comment]
@traducer latest version published to NPM. 🚀

**Pull request merged**
